version: '3'

services:
  web:
    build: .
    ports:
      - "82:82"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=symfony
    depends_on:
      - mysql
  mysql:
    image: mysql:5
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
